name: Takibi
options:
  minimumXcodeGenVersion: 2.38.0
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
settings:
  base:
    SWIFT_VERSION: 5.9
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    CURRENT_PROJECT_VERSION: 3
    MARKETING_VERSION: 0.1.0
    ENABLE_USER_SCRIPT_SANDBOXING: true
targets:
  Takibi:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Sources
        excludes:
          - Resources
      - path: Sources/Resources/Assets.xcassets
        buildPhase: resources
      - path: Sources/Resources/PrivacyInfo.xcprivacy
        buildPhase: resources
      - path: Sources/Resources/Icon-60@2x.png
        buildPhase: resources
      - path: Sources/Resources/Icon-60@3x.png
        buildPhase: resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.supamucho76.takibi
        PRODUCT_NAME: Takibi
        INFOPLIST_FILE: Sources/Resources/Info.plist
        PRODUCT_MODULE_NAME: Takibi
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_INCLUDE_ALL_APPICON_ASSETS: true
        INFOPLIST_KEY_CFBundleIconName: AppIcon
        TARGETED_DEVICE_FAMILY: "1"
        SUPPORTS_MACCATALYST: false
        ENABLE_PREVIEWS: true
    scheme:
      testTargets:
        - TakibiTests
      gatherCoverageData: true
  TakibiTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Tests
    dependencies:
      - target: Takibi
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.supamucho76.takibiTests
        GENERATE_INFOPLIST_FILE: true
